# @file bootchain_build.yml
#
# This workflow is responsible for building and verifying the ODP version of the bootchain firmware for a Radxa Orion
# O6 platform
#
##
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: MIT
##

name: bootchain-build

# Restrict GitHub permissions to only what is necessary for the workflow
permissions:
  contents: read

# Trigger the workflow on pull requests to the main branch and allow manual triggering
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

# Cancel in-progress runs for the same PR/branch
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  # Build the bootchain using Podman per the documentation
  build-podman:
    runs-on: ubuntu-latest
    name: Compile Repository
    steps:
      - name: Clone Repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build Container
        run: podman build -q -t odp-orion-o6-build -f .devcontainer/Dockerfile .

      - name: Update Workspace Ownership
        run: |
          podman run --rm \
            --user root \
            -v "${{ github.workspace }}:/workspace" \
            odp-orion-o6-build \
            chown -R 1000:1000 /workspace

      - name: Build Firmware
        run: |
          podman run --rm \
            -w /workspace \
            -v "${{ github.workspace }}:/workspace" \
            odp-orion-o6-build \
            make all

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ODP_Orion_O6_Bootchain
          path: build/postbuild/bootchain/
